// <auto-generated />
using System;
using ClaudeTradingBot.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClaudeTradingBot.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20260315143144_AddAppUser")]
    partial class AddAppUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("ClaudeTradingBot.Models.AccountSettingsEntity", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PaperTradingJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskSettingsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StrategyPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TradeLockerJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WatchListJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("AccountSettings");
                });

            modelBuilder.Entity("ClaudeTradingBot.Models.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("ClaudeTradingBot.Models.DailyPnL", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PeakEquity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PortfolioValue")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("RealizedPnL")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("TradeCount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnrealizedPnL")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("Date", "AccountId")
                        .IsUnique();

                    b.ToTable("DailyPnLs");
                });

            modelBuilder.Entity("ClaudeTradingBot.Models.EngineStateSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CleanShutdown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenPositionCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenPositionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ShutdownAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("WasKillSwitchActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasPaused")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WasRunning")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ShutdownAt");

                    b.ToTable("EngineStateSnapshots");
                });

            modelBuilder.Entity("ClaudeTradingBot.Models.GlobalSettingsEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Key");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("ClaudeTradingBot.Models.GridState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CenterPrice")
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("GridSpacingPips")
                        .HasColumnType("REAL");

                    b.Property<string>("LevelsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LotSizePerLevel")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalPnL")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("AccountId", "Symbol");

                    b.ToTable("GridStates");
                });

            modelBuilder.Entity("ClaudeTradingBot.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("BrokerPositionId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CurrentPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrokerPositionId")
                        .IsUnique();

                    b.HasIndex("Symbol");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("ClaudeTradingBot.Models.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BrokerOrderId")
                        .HasColumnType("TEXT");

                    b.Property<string>("BrokerPositionId")
                        .HasColumnType("TEXT");

                    b.Property<double>("ClaudeConfidence")
                        .HasColumnType("REAL");

                    b.Property<string>("ClaudeReasoning")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("EntryPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ExecutedPrice")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RealizedPnL")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("SetupType")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SpreadAtEntry")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SetupType");

                    b.HasIndex("Status");

                    b.HasIndex("Symbol");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("ClaudeTradingBot.Models.TradingLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Timestamp");

                    b.ToTable("TradingLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
